language: node_js
node_js:
- 4.2
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libcairo2-dev
    - libjpeg8-dev
    - libpango1.0-dev
    - libgif-dev
    - build-essential
before_script:
- npm install -g grunt-cli
env:
- CXX=g++-4.8
deploy:
  provider: npm
  email: jononor@gmail.com
  api_key:
    secure: XNPR9aJFCmw8OfQGIKbCMrWgbjf+TaDuEDiT/sY7zbWr8NMTL//Rfg6jGcTCZ/uNpEw6l+z8iSkIeDdrKgoKZ319mCTK8IrQVuot8TSaqR2Xf2pGCRIocUDnXkbGCtWEReRt575AAdDW52p4CibS/FJE6GHd+fo7I5RmcUtg/zA=
  on:
    tags: true
    repo: noflo/noflo-canvas
